#---------------------------------------
# GitHub Action LabDevOps1

# All rights reserved...  Joke)
#---------------------------------------
name: Build-Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build project and upload artifacts
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: tg-artifact
          path: /app
          retention-days: 5
  
  docker_app:
    name: Docker Containerization
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags:  ${{ secrets.DOCKERHUB_USERNAME }}/testdev:latest
          
          
  deploy_on_local:
    name: Deploy on PC
    runs-on: self-hosted
    needs: docker_app

    steps:
      - name: Pull docker image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/testdev:latest

      - name: Run docker container
        run: |
          docker run --name test ${{ secrets.DOCKERHUB_USERNAME }}/testdev:latest ${{ secrets.TELEGRAM_TOKEN }}
          
          
  send_telegram:
    name: Send artifacts to telegram
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: tg-artifact
      - name: ls 
        run: ls -la 
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: bot.py
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            Repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            
          
  analys_code:
    name: Analyse Project code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
          python-version: 3.11
    - name: analys
      run: |
          python -m pip install --upgrade pip
          pip install black
          black --check . 
  

          
  
