#---------------------------------------
# GitHub Action LabDevOps

# All rights reserved...  Joke)
#---------------------------------------

# This workflow will install Python dependencies


name: Build->Deploy->Upload

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Pytest
        run: pytest --verbosity=2 --showlocals
      
      - name: Build
        run: pyinstaller --onefile main.py
      
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: tg-artifact
          path: dist/

