#---------------------------------------
# GitHub Action LabDevOps

# All rights reserved...  Joke)
#---------------------------------------

# This workflow will install Python dependencies


name: Build->Deploy->Upload

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Pytest
        run: pytest --verbosity=2 --showlocals
      
      - name: Build
        run: pyinstaller --onefile main.py
      
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: tg-artifact
          path: dist/
          
  fix_code:
    name: make code correct
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format code with black
        run: |
          pip install black
          black .
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: "Itsimple1"
          author_email: "Itsimple1@users.noreply.github.com"
          message: "Format code with black"
          add: "."
          branch: "main"
